config/routes.rb
Rails.application.routes.draw do
  # set root page to index method in root controller
  root to: 'root#index'

  # set workout routes
  resources :workouts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/motivation.rb
class Motivation < ApplicationRecord
end

app/models/workout.rb
class Workout < ApplicationRecord
	# validates :name, :muscle_group, :sets, :reps, :date, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController
	# homepage method
	def index
	end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	# index method
	def index
		# list all workouts with ID in descending order
		@workouts = Workout.all.order(id: :desc)
		# initiate randomizer for quotes
		num = rand(1..10)
		# set variable to random quote from database
		@motivation = Motivation.find(num)
	end

	# show method
	def show
		# find specified workout
		@workout = Workout.find(params[:id])
		# list all workouts with ID in desc order
		@workouts = Workout.all.order(id: :desc)
		# initiate randomizer for quotes
		num = rand(1..10)
		# set variable to random quote from db
		@motivation = Motivation.find(num)
	end

	# new method
	def new
		# create new workout
		@workout = Workout.new
		# initiate randomizer for quote
		num = rand(1..10)
		# set variable to random quote
		@motivation = Motivation.find(num)
	end

	# create method
	def create
		# create a new workout with params from private method
		@workout = Workout.new(workout_params)
		# set variable to random number
		num = rand(1..10)
		# declare quote variable
		@motivation = Motivation.find(num)
		# if the workout is saved successfully
		if @workout.save
			# redirect to the show page of that workout
			redirect_to workout_path(@workout)
		# otherwise
		else
			# refresh the New page
			render :new
		end
	end

	# edit method
	def edit
		# pull in set workout
		@workout = Workout.find(params[:id])
		# pull random number
		num = rand(1..10)
		# set variable to random quote
		@motivation = Motivation.find(num)
	end

	# update method
	def update
		# set selected workout to variable
		@workout = Workout.find(params[:id])
		# if the workout is successfully updated
		if @workout.update(workout_params)
			# redirect to the updated workouts page
			redirect_to workout_path(@workout)
		# otherwise
		else
			# refresh the page
			redirect_to workout_edit_path(@workout)
		end
	end

	# destroy method
	def destroy
		# find specified workout
		@workout = Workout.find(params[:id])
		# list all motivation quotes
		@motivations = Motivation.all
		# delete workout
		@workout.delete
		# redirect to index page after deletion
		redirect_to workouts_path
	end

	private
	# set workout params in private method
	def workout_params
		# require columns in table
		params.require(:workout).permit(:name, :muscle_group, :sets, :reps, :date)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WokroutLogApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/root/index.html.erb
<div class="root-container"	>
	<h1 class="root-header"> WORKOUT LOGGER </h1>
	<div class="link-container">
		<div class="root-form">
			<%# set View Workouts button to redirect to list of workouts %>
			<%= button_to 'View Workouts', workouts_path(@workouts), :class => "root-link", :method => :get %>		
		</div>
		<div class="root-form">
			<%# set Add Workout button to navigate to create workout page %>
			<%= button_to 'Add Workout', new_workout_path(@workout), :class => "root-link", :method => :get %>
		</div>
	</div>

	<footer class="root-footer">Made by Dan Levenson, 2017</footer>
</div>

app/views/workouts/_footer.html.erb
<footer class="partial-footer">Made by Dan Levenson, 2017</footer>

app/views/workouts/_form.html.erb
<div class="form-container">
	<%# create form to set values to be edited or created in entry %>
	<%# each field represents a different column in the workouts table %>
	<%= form_for @workout do |f| %>
		<p class="workout-field"> Name of Workout:  <%= f.text_field :name, placeholder: "Name of Workout", required: true, :class => 'workout-field' %></p>
		<p class="workout-field">Muslce Group:  <%= f.text_field :muscle_group, placeholder: "Muscle Group", required: true, :class => 'workout-field' %></p>
		<p class="workout-field">Sets:  <%= f.number_field :sets, placeholder: "Sets", required: true, :class => 'workout-field' %></p>
		<p class="workout-field">Reps:  <%= f.number_field :reps, placeholder: "Reps", required: true, :class => 'workout-field' %></p>
		<p class="workout-field">Weight:  <%= f.number_field :weight, placeholder: "Weight (if applicable)", :class => 'workout-field' %></p>
		<p class="workout-field">Date:  <%= f.text_field :date, placeholder: "Date", required: true, :class => 'workout-field' %></p>
		<%= f.submit "Submit", :class => 'show-link'%>
	<% end %>
</div>

app/views/workouts/_quote.html.erb
<%# this view renders the quote partial that is reused in other views %>
<div class="quote-container">
	<h3><%= @motivation.quote %></h3>
	<h5><%= @motivation.author %></h5>
</div>

app/views/workouts/edit.html.erb
<div class="edit-container">
	<h1 class="index-header">WORKOUT LOGGER</h1>
	<div class="show-form">
		<%# list button to view all workouts %>
		<%= button_to 'View Workouts', workouts_path(@workouts), :class => "show-link", :method => :get %>		
	</div>
	<h3 class="index-subheader" >Edit Workout Below</h3>
	<div class="edit-subcont">
		<%# render form and quote partials %>
		<%= render partial: 'form' %>
		<%= render partial: 'quote' %>
	</div>
	<%= render partial: 'footer' %>
</div>

app/views/workouts/index.html.erb
<div class="index-container">
	<h1 class="index-header">WORKOUT LOGGER</h1>
	<div class="index-form">
		<%= button_to 'Add Workout', new_workout_path(@workout), :class => "show-link", :method => :get %>
	</div>
	<h3 class="index-subheader">Workout Log Below</h3>
	<div class="index-subcont">
		<ul class="workout-ul">
			<%# for each workout  %>
			<% @workouts.each do |workout| %>
			<%# create a list item for each workout that will link to the show view %>
			<li class="workout-li"><%= link_to workout.name, workout_path(workout)%>, <%= workout.date %></li>
			<% end %>
		</ul>
		<div class="index-quote">
			<%# render quote partial %>
			<%= render partial: 'quote'%>
		</div>
	</div>
	<div class="index-footer">
		<%= render partial: 'footer'%>
	</div>
</div>

app/views/workouts/new.html.erb
<div class="new-container">
	<h1 class="index-header">WORKOUT LOGGER</h1>
	<div class="show-form">
		<%# link to index workouts view %>
		<%= button_to 'View Workouts', workouts_path(@workouts), :class => "show-link", :method => :get %>		
	</div>
	<h3 class="index-subheader">Fill Out Workout Info Below</h3>
	<div class="new-subcont">
		<%# render form and quote partials %>
		<%= render partial: 'form' %>
		<%= render partial: 'quote' %>	
	</div>
	<%= render partial: 'footer' %>
</div>

app/views/workouts/show.html.erb
<div class="show-container">
	<h1 class="show-header">WORKOUT LOGGER</h1>
	<div class="show-form">
		<%# link to index workouts view %>
		<%= button_to 'View Workouts', workouts_path(@workouts), :class => "show-link", :method => :get %>		
	</div>
	<div class="show-subcont">
		<div class="show-info">
			<%# show workout information %>
			<h3 class="workout-header"><%= @workout.name %></h3>
			<h5 class="workout-info">Wokrout Type: <%= @workout.name %></h5>
			<h5 class="workout-info">Muscle Group: <%= @workout.muscle_group %></h5>
			<h5 class="workout-info">Sets: <%= @workout.sets %></h5>
			<h5 class="workout-info">Reps: <%= @workout.reps %></h5>
			<h5 class="workout-info">Weight: <%= @workout.weight %></h5>
			<h5 class="workout-info">Date: <%= @workout.date %></h5>
		</div>
		<div class="show-quote">
			<%# render quote partial %>
			<%= render partial: 'quote' %>
		</div>
	</div>
	<div class="show-UD">
		<%# link to edit workout view %>
		<%= button_to 'Edit Workout', edit_workout_path(@workout), :class => "show-link", :method => :get %>
		<%# create form and button to delete workout %>
		<%= form_for @workout, :class => 'show-link', html: {method: 'delete'} do |f| %>
			<%= f.submit "Delete Workout", :class => "show-link" %>
		<% end %>
	</div>
	<div class="show-footer">
		<%= render partial: 'footer' %>
	</div>
</div>